-- 1) instructional_status enum (single authoritative status; replaces brittle boolean logic)
DO $$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'instructional_status') THEN
    CREATE TYPE instructional_status AS ENUM (
      'NONE',           -- does not count
      'MANUAL_COUNTS',  -- user opted in to count
      'PLAN_PLACEHOLDER',-- generated by Plan My Year
      'PLAN_LOCKED',    -- future: locked into plan
      'EXCLUDED'        -- future: explicitly excluded from compliance
    );
  END IF;
END $$;

ALTER TABLE events
ADD COLUMN IF NOT EXISTS instructional_status text NULL;

COMMENT ON COLUMN events.instructional_status IS 'Authoritative: NONE, MANUAL_COUNTS, PLAN_PLACEHOLDER, PLAN_LOCKED, EXCLUDED. Derive counts_toward_plan = status IN (MANUAL_COUNTS, PLAN_PLACEHOLDER).';

-- Backfill from existing counts_toward_plan / is_placeholder / generated_by
UPDATE events e
SET instructional_status = CASE
  WHEN e.is_placeholder = true AND e.generated_by = 'plan_year' THEN 'PLAN_PLACEHOLDER'
  WHEN e.counts_toward_plan = true THEN 'MANUAL_COUNTS'
  ELSE 'NONE'
END
WHERE e.instructional_status IS NULL;

-- Optional: add check constraint (allow text for flexibility with enum values)
ALTER TABLE events DROP CONSTRAINT IF EXISTS events_instructional_status_check;
ALTER TABLE events ADD CONSTRAINT events_instructional_status_check
  CHECK (instructional_status IS NULL OR instructional_status IN ('NONE', 'MANUAL_COUNTS', 'PLAN_PLACEHOLDER', 'PLAN_LOCKED', 'EXCLUDED'));

-- 2) academic_year_child_progress cache (O(children) plan health)
CREATE TABLE IF NOT EXISTS academic_year_child_progress (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  academic_year_id uuid NOT NULL REFERENCES academic_years(id) ON DELETE CASCADE,
  child_id uuid NOT NULL REFERENCES children(id) ON DELETE CASCADE,
  instructional_minutes_total integer NOT NULL DEFAULT 0,
  instructional_days_total integer NOT NULL DEFAULT 0,
  last_recomputed_at timestamptz NOT NULL DEFAULT now(),
  UNIQUE(academic_year_id, child_id)
);

CREATE INDEX IF NOT EXISTS idx_academic_year_child_progress_ay
  ON academic_year_child_progress(academic_year_id);
CREATE INDEX IF NOT EXISTS idx_academic_year_child_progress_child
  ON academic_year_child_progress(child_id);

COMMENT ON TABLE academic_year_child_progress IS 'Incremental cache for plan health; update on instructional event create/update/delete and placeholder generation.';

-- 3) Academic year plan ownership invariant: if counts_toward_plan then academic_year_id must be set
-- Clean up any existing rows that violate the invariant (orphan instructional events)
UPDATE events
SET counts_toward_plan = false, instructional_status = 'NONE'
WHERE counts_toward_plan = true AND academic_year_id IS NULL;

ALTER TABLE events DROP CONSTRAINT IF EXISTS events_instructional_requires_academic_year;
ALTER TABLE events ADD CONSTRAINT events_instructional_requires_academic_year
  CHECK (counts_toward_plan = false OR academic_year_id IS NOT NULL);
